# Data Engineering 
Â© Explore Data Science Academy
## Moving Big Data Predict: Python Processing MCQ

Use the CSV output file generated by your pipeline to answer the below questions

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("/Users/leonsmith/Code_Courses/Explore_DE/Moving_Big_Data/Predict/Output/historical_stock_data.csv")

In [3]:
df.head()

,stock_date,open_value,high_value,low_value,close_value,volume_traded,daily_percent_change,value_change,company_name
0,2015-10-27,65.170,65.170,63.056,63.187,36229,-3.042811,-1.983,tmusp
1,2015-10-28,64.449,64.449,63.431,64.085,61025,-0.564788,-0.364,tmusp
2,2015-10-29,63.514,63.514,60.858,61.511,139471,-3.153635,-2.003,tmusp
3,2015-10-30,61.119,62.363,60.950,62.214,46703,1.791587,1.095,tmusp
4,2015-11-02,61.970,62.859,61.970,62.821,411208,1.373245,0.851,tmusp

#### 1. What is the most common data type of the columns in your processed data?

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2054899 entries, 0 to 2054898
Data columns (total 9 columns):
 #   Column                Dtype
---  ------                -----
 0   stock_date            object
 1   open_value            float64
 2   high_value            float64
 3   low_value             float64
 4   close_value           float64
 5   volume_traded         int64
 6   daily_percent_change  float64
 7   value_change          float64
 8   company_name          object
dtypes: float64(6), int64(1), object(2)
memory usage: 141.1+ MB

#### 2. How many rows does the output dataframe have?

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2054899 entries, 0 to 2054898
Data columns (total 9 columns):
 #   Column                Dtype
---  ------                -----
 0   stock_date            object
 1   open_value            float64
 2   high_value            float64
 3   low_value             float64
 4   close_value           float64
 5   volume_traded         int64
 6   daily_percent_change  float64
 7   value_change          float64
 8   company_name          object
dtypes: float64(6), int64(1), object(2)
memory usage: 141.1+ MB

#### 3. What is the sum of the value_change column?

In [7]:
df["value_change"].sum()

-8977.026547999994

#### 4. What is the mean of the value_change column?

In [9]:
df["value_change"].mean()

-0.004368597458074579

#### 5. What is the mean open_value?

In [10]:
df["open_value"].mean()

24.828452685552428

#### 6. What is the mean close_value?

In [11]:
df["close_value"].mean()

24.824084088094356

#### 7. What are the minimum and maximum values in the stock_date column?

In [12]:
df["stock_date"].min()

'1962-01-02'

#### 8. How many distinct values are in the company_name column?

In [15]:
df["company_name"].nunique()

995

#### 9.  What type of file format is more efficient in terms of storage space?